# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

theme = "default"
"spotify" = "ó°“‡ "
"alacritty" = "ï„  "
"xfce4-terminal" = "ï„  "
"github" = "ï„“ "
"rust" = "î¨"
"code" = "ó°¨ "
"genymotion" = "ó°“·"
"google" = "ï† "
"gitlab" = "ïŠ– "
"private browsing" = "ïˆ›"
"vlc" = "ó°•¼"
"firefox" = "ï‰© "
"chrome" = "ï‰¨ "
"opera" = "ï‰ª "
"microsoft-edge" ="ó°‡©"
"geary" = "î¬œ "
"file manager" = "ï¼ "
"libreoffice calc" = "ïƒ "
"libreoffice writer" = "ïœ˜"
"whatsapp" = "ïˆ²"
"pcmanfm" = "ï¼ "
"thunar" = "ï¼ "
"libreoffice" = "ï£…"
"nvim " = "îŸ… "
"neovim"="îŸ… "
"telegram" = "ï‹† "
"org.gnome.Software"="ó°Š¬"
"gthumb" = "ï€¾ "
"menu" = "ï¡œ "
"calculator" = "ï—«"
"transmission" = "ï€™ "
"videostream" = "ï˜˜"
"mpv" = "ïœª "
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"
"mousepad" = "ó°"
"sublime_text"="îš–"
"youtube"="ó°—ƒ"
"blueman-manager"="ó°¥°"
"jetbrains-studio"="ó°€´"
"react native"="îº"
"docker"="ó°¡¨"
"file-roller" ='îšª'
"kvantum"="ó°°Š"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
